export const GET_ALL_POST = "GET_ALL_POST"

export const CREATE_NEW_POST = "CREATE_NEW_POST"

export const ERROR_CREATE_NEW_POST = "ERROR_CREATE_NEW_POST"

export const DELETE_POST = "DELETE_POST"

export const ERROR_DELETE_POST = "ERROR_DELETE_POST"

export const GET_ALL_POST_FAILURE = "GET_ALL_POST_FAILURE"

export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE"

export const SET_PER_PAGE = "SET_PER_PAGE"
