// POST
export const GET_ALL_POST = "GET_ALL_POST"

export const CREATE_NEW_POST = "CREATE_NEW_POST"

export const ERROR_CREATE_NEW_POST = "ERROR_CREATE_NEW_POST"

export const DELETE_POST = "DELETE_POST"

export const ERROR_DELETE_POST = "ERROR_DELETE_POST"

export const GET_ALL_POST_FAILURE = "GET_ALL_POST_FAILURE"

export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE"

export const SET_PER_PAGE = "SET_PER_PAGE"

export const POST_DELETE_ALL_INFORM = "POST_DELETE_ALL_INFORM"

export const POST_PLUS_OR_MINUS_LIKE = "POST_PLUS_OR_MINUS_LIKE"

export const POST_PUT = "POST_PUT"

export const SAVE_IMG_POST = "SAVE_IMG_POST"

export const SAVE_IMG_POST_PUT = "SAVE_IMG_POST_PUT"

export const TOGLE_IS_FETCHING = "TOGLE_IS_FETCHING"

export const TOGLE_IS_LOAD_FETCHING_POST = "TOGLE_IS_LOAD_FETCHING_POST"

// USER
export const USER_IS_AUTH = "USER_IS_AUTH"

export const USER_DELETE_ALL_INFORM = "USER_DELETE_ALL_INFORM"

export const GET_ALL_USERS = "GET_ALL_USERS"

export const SET_CURRENT_PAGE_USERS = "SET_CURRENT_PAGE_USERS"

export const DELETE_USER = "DELETE_USER"

export const USER_UPDATE_INFORM = "USER_UPDATE_INFORM"

export const SAVE_AVATAR_USER = "SAVE_AVATAR_USER"

export const SHOW_INFO_CHOOSE_USER = "SHOW_INFO_CHOOSE_USER"

export const TOGLE_IS_FETCHING_USER = "TOGLE_IS_FETCHING_USER"

// AUTH

export const INFORM_USER = "INFORM_USER"
